export type PromptScope = "plant" | "diagnosis" | "species" | "general";

export type PromptRequirement =
  | "hasSpecies"
  | "hasDiagnosis"
  | "toxic"
  | "overdue"
  | "neverWatered";

export interface ChatPrompt {
  id: string;
  scope: PromptScope;
  text: string;
  requires?: PromptRequirement;
}

export const CHAT_PROMPTS: ChatPrompt[] = [
  { id: "p1", scope: "plant", text: "Com que frequência eu rego {{planta}}?" },
  { id: "p2", scope: "plant", text: "Como sei que estou regando demais?" },
  { id: "p3", scope: "plant", text: "Como sei que estou regando de menos?" },
  { id: "p4", scope: "plant", text: "Quanta luz {{planta}} precisa?" },
  { id: "p5", scope: "plant", text: "Posso deixar {{planta}} no banheiro?" },
  { id: "p6", scope: "plant", text: "Posso deixar {{planta}} no quarto?" },
  { id: "p7", scope: "plant", text: "Ela aguenta sol direto da tarde?" },
  { id: "p8", scope: "plant", text: "Qual o melhor lugar da casa pra ela?" },
  { id: "p9", scope: "plant", text: "Preciso mudar ela de lugar no inverno?" },
  { id: "p10", scope: "plant", text: "E no verão, muda alguma coisa?" },
  { id: "p11", scope: "plant", text: "Qual substrato combina com {{planta}}?" },
  { id: "p12", scope: "plant", text: "Preciso colocar pedra no fundo do vaso?" },
  { id: "p13", scope: "plant", text: "Como sei que chegou a hora de trocar o vaso?" },
  { id: "p14", scope: "plant", text: "Que tamanho de vaso é o certo agora?" },
  { id: "p15", scope: "plant", text: "Vaso de barro ou de plástico pra ela?" },
  { id: "p16", scope: "plant", text: "Posso trocar o vaso nessa época do ano?" },
  { id: "p17", scope: "plant", text: "Como faço a troca de vaso sem machucar a raiz?" },
  { id: "p18", scope: "plant", text: "Que adubo eu uso em {{planta}}?" },
  { id: "p19", scope: "plant", text: "De quanto em quanto tempo eu adubo?" },
  { id: "p20", scope: "plant", text: "Posso adubar no inverno?" },
  { id: "p21", scope: "plant", text: "Dá pra usar borra de café como adubo?" },
  { id: "p22", scope: "plant", text: "Como podo {{planta}} sem estragar?" },
  { id: "p23", scope: "plant", text: "Qual a época certa de podar?" },
  { id: "p24", scope: "plant", text: "Posso cortar as folhas secas?" },
  { id: "p25", scope: "plant", text: "Como faço muda de {{planta}}?" },
  { id: "p26", scope: "plant", text: "Enraíza na água ou direto na terra?" },
  { id: "p27", scope: "plant", text: "Quanto tempo demora pra pegar a muda?" },
  { id: "p28", scope: "plant", text: "Ela cresce até que tamanho?" },
  { id: "p29", scope: "plant", text: "Como faço ela crescer mais cheia?" },
  { id: "p30", scope: "plant", text: "Ela dá flor? Em que época?" },
  { id: "p31", scope: "plant", text: "Por que ela parou de crescer?" },
  { id: "p32", scope: "plant", text: "Preciso limpar as folhas dela?" },
  { id: "p33", scope: "plant", text: "Posso passar óleo pra dar brilho na folha?" },
  { id: "p34", scope: "plant", text: "Ela gosta de umidade? Preciso vaporizar?" },
  { id: "p35", scope: "plant", text: "Ar-condicionado no cômodo atrapalha?" },
  { id: "p36", scope: "plant", text: "Vento forte na varanda é problema?" },
  { id: "p37", scope: "plant", text: "Vou viajar duas semanas, o que faço com ela?" },
  { id: "p38", scope: "plant", text: "Posso deixar ela na chuva?" },
  { id: "p39", scope: "plant", text: "Água da torneira serve ou preciso filtrar?" },
  { id: "p40", scope: "plant", text: "Melhor regar de manhã ou à noite?" },
  { id: "p41", scope: "plant", text: "Rego por cima ou coloco água no pratinho?" },
  { id: "p42", scope: "plant", text: "Pratinho com água parada faz mal?" },
  { id: "p43", scope: "plant", text: "Como sei se a terra ainda está úmida?" },
  { id: "p44", scope: "plant", text: "Ela precisa de tutor ou suporte?" },
  { id: "p45", scope: "plant", text: "Posso plantar outra junto no mesmo vaso?" },
  { id: "p46", scope: "plant", text: "Mudei ela de lugar e ela ficou estranha, é normal?" },
  { id: "p47", scope: "plant", text: "Comprei agora, o que faço nos primeiros dias?" },
  { id: "p48", scope: "plant", text: "Preciso trocar a terra da loja?" },
  { id: "p49", scope: "plant", text: "Como cuido dela na época mais seca?" },
  { id: "p50", scope: "plant", text: "Ela sobrevive se eu esquecer de regar?" },

  {
    id: "t1",
    scope: "plant",
    requires: "toxic",
    text: "Ela é tóxica pro meu gato, o que eu faço?",
  },
  {
    id: "t2",
    scope: "plant",
    requires: "toxic",
    text: "Onde deixo ela longe do meu cachorro?",
  },
  {
    id: "t3",
    scope: "plant",
    requires: "toxic",
    text: "Meu pet encostou nela, devo me preocupar?",
  },
  {
    id: "o1",
    scope: "plant",
    requires: "overdue",
    text: "Passei do dia de regar, rego mais dessa vez?",
  },
  {
    id: "o2",
    scope: "plant",
    requires: "overdue",
    text: "Esqueci dela um tempo, como recupero?",
  },
  {
    id: "n1",
    scope: "plant",
    requires: "neverWatered",
    text: "Acabei de cadastrar, quando devo regar a primeira vez?",
  },

  {
    id: "d1",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "O que eu faço primeiro pra tratar isso?",
  },
  {
    id: "d2",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Em quanto tempo devo ver melhora?",
  },
  {
    id: "d3",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Preciso isolar ela das outras plantas?",
  },
  {
    id: "d4",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Isso passa pras outras plantas de casa?",
  },
  {
    id: "d5",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Corto as folhas afetadas ou deixo?",
  },
  {
    id: "d6",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Devo parar de regar enquanto trata?",
  },
  {
    id: "d7",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Que tipo de produto resolve isso?",
  },
  {
    id: "d8",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Dá pra tratar sem comprar nada?",
  },
  {
    id: "d9",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Como evito que volte?",
  },
  {
    id: "d10",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Ela ainda tem salvação?",
  },
  {
    id: "d11",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Preciso trocar a terra por causa disso?",
  },
  {
    id: "d12",
    scope: "diagnosis",
    requires: "hasDiagnosis",
    text: "Posso continuar adubando durante o tratamento?",
  },

  { id: "s1", scope: "species", text: "{{especie}} é fácil de cuidar?" },
  { id: "s2", scope: "species", text: "{{especie}} dá bem dentro de casa?" },
  { id: "s3", scope: "species", text: "Quanto sol {{especie}} precisa?" },
  { id: "s4", scope: "species", text: "{{especie}} é boa pra quem esquece de regar?" },
  { id: "s5", scope: "species", text: "{{especie}} cresce rápido?" },
  { id: "s6", scope: "species", text: "{{especie}} dá em vaso pequeno?" },
  { id: "s7", scope: "species", text: "{{especie}} serve pra apartamento sem varanda?" },
  { id: "s8", scope: "species", text: "{{especie}} aguenta friagem?" },
  { id: "s9", scope: "species", text: "{{especie}} é segura pra quem tem pet?" },
  { id: "s10", scope: "species", text: "Qual o maior erro de quem cuida de {{especie}}?" },
  { id: "s11", scope: "species", text: "{{especie}} dá flor?" },
  { id: "s12", scope: "species", text: "Como faço muda de {{especie}}?" },
  { id: "s13", scope: "species", text: "{{especie}} precisa de muita água?" },
  { id: "s14", scope: "species", text: "Onde {{especie}} fica melhor na casa?" },
  { id: "s15", scope: "species", text: "{{especie}} pega praga com facilidade?" },
  { id: "s16", scope: "species", text: "Existe alguma parecida com {{especie}} mais fácil?" },
  { id: "s17", scope: "species", text: "{{especie}} vive muitos anos?" },
  { id: "s18", scope: "species", text: "{{especie}} pode ficar em vaso pendurado?" },

  { id: "g1", scope: "general", text: "Qual planta é boa pra quem está começando?" },
  { id: "g2", scope: "general", text: "Que planta vai bem em quarto sem sol direto?" },
  { id: "g3", scope: "general", text: "Qual planta aguenta eu viajar bastante?" },
  { id: "g4", scope: "general", text: "Que planta é segura tendo gato em casa?" },
  { id: "g5", scope: "general", text: "Como escolho o vaso certo?" },
  { id: "g6", scope: "general", text: "Preciso de vaso com furo embaixo?" },
  { id: "g7", scope: "general", text: "Qual terra eu compro pra plantas de casa?" },
  { id: "g8", scope: "general", text: "Com que frequência se aduba planta de vaso?" },
  { id: "g9", scope: "general", text: "Por que as folhas ficam amarelas?" },
  { id: "g10", scope: "general", text: "Por que a ponta da folha fica marrom?" },
  { id: "g11", scope: "general", text: "O que é aquela mosquinha da terra?" },
  { id: "g12", scope: "general", text: "Como deixo minhas plantas prontas pra viagem?" },
  { id: "g13", scope: "general", text: "Planta de banheiro precisa de cuidado diferente?" },
  { id: "g14", scope: "general", text: "Dá pra ter planta em casa sem janela boa?" },
  { id: "g15", scope: "general", text: "Quantas vezes por semana devo regar no geral?" },
  { id: "g16", scope: "general", text: "Como sei se meu vaso está pequeno demais?" },
  { id: "g17", scope: "general", text: "Que planta cresce rápido e enche o cantinho?" },
  { id: "g18", scope: "general", text: "Como monto um cantinho verde na sala?" },
  { id: "g19", scope: "general", text: "Planta perto da janela pega vento demais?" },
  { id: "g20", scope: "general", text: "Qual planta combina com cozinha?" },
];
