export type PromptScope = "plant" | "diagnosis" | "species" | "general";

export type PromptRequirement =
  | "hasSpecies"
  | "hasDiagnosis"
  | "toxic"
  | "overdue"
  | "neverWatered";

export const CHAT_PROMPT_IDS = [
  "p1",
  "p2",
  "p3",
  "p4",
  "p5",
  "p6",
  "p7",
  "p8",
  "p9",
  "p10",
  "p11",
  "p12",
  "p13",
  "p14",
  "p15",
  "p16",
  "p17",
  "p18",
  "p19",
  "p20",
  "p21",
  "p22",
  "p23",
  "p24",
  "p25",
  "p26",
  "p27",
  "p28",
  "p29",
  "p30",
  "p31",
  "p32",
  "p33",
  "p34",
  "p35",
  "p36",
  "p37",
  "p38",
  "p39",
  "p40",
  "p41",
  "p42",
  "p43",
  "p44",
  "p45",
  "p46",
  "p47",
  "p48",
  "p49",
  "p50",
  "p51",
  "p52",
  "p53",
  "p54",
  "p55",
  "p56",
  "p57",
  "p58",
  "p59",
  "p60",
  "p61",
  "p62",
  "p63",
  "p64",
  "p65",
  "p66",
  "p67",
  "p68",
  "p69",
  "p70",
  "p71",
  "p72",
  "p73",
  "p74",
  "p75",
  "p76",
  "p77",
  "p78",
  "p79",
  "p80",
  "p81",
  "p82",
  "p83",
  "p84",
  "p85",
  "p86",
  "p87",
  "p88",
  "p89",
  "p90",
  "t1",
  "t2",
  "t3",
  "t4",
  "t5",
  "o1",
  "o2",
  "o3",
  "n1",
  "n2",
  "d1",
  "d2",
  "d3",
  "d4",
  "d5",
  "d6",
  "d7",
  "d8",
  "d9",
  "d10",
  "d11",
  "d12",
  "d13",
  "d14",
  "d15",
  "d16",
  "d17",
  "d18",
  "d19",
  "d20",
  "d21",
  "d22",
  "d23",
  "d24",
  "d25",
  "s1",
  "s2",
  "s3",
  "s4",
  "s5",
  "s6",
  "s7",
  "s8",
  "s9",
  "s10",
  "s11",
  "s12",
  "s13",
  "s14",
  "s15",
  "s16",
  "s17",
  "s18",
  "s19",
  "s20",
  "s21",
  "s22",
  "s23",
  "s24",
  "s25",
  "s26",
  "s27",
  "s28",
  "s29",
  "s30",
  "s31",
  "s32",
  "s33",
  "s34",
  "s35",
  "g1",
  "g2",
  "g3",
  "g4",
  "g5",
  "g6",
  "g7",
  "g8",
  "g9",
  "g10",
  "g11",
  "g12",
  "g13",
  "g14",
  "g15",
  "g16",
  "g17",
  "g18",
  "g19",
  "g20",
  "g21",
  "g22",
  "g23",
  "g24",
  "g25",
  "g26",
  "g27",
  "g28",
  "g29",
  "g30",
  "g31",
  "g32",
  "g33",
  "g34",
  "g35",
  "g36",
  "g37",
  "g38",
  "g39",
  "g40",
  "g41",
  "g42",
  "g43",
  "g44",
] as const;

export type ChatPromptId = (typeof CHAT_PROMPT_IDS)[number];

export interface ChatPrompt {
  id: ChatPromptId;
  scope: PromptScope;
  requires?: PromptRequirement;
  needsSpecies?: boolean;
}

export const CHAT_PROMPTS: ChatPrompt[] = [
  { id: "p1", scope: "plant" },
  { id: "p2", scope: "plant" },
  { id: "p3", scope: "plant" },
  { id: "p4", scope: "plant" },
  { id: "p5", scope: "plant" },
  { id: "p6", scope: "plant" },
  { id: "p7", scope: "plant" },
  { id: "p8", scope: "plant" },
  { id: "p9", scope: "plant" },
  { id: "p10", scope: "plant" },
  { id: "p11", scope: "plant" },
  { id: "p12", scope: "plant" },
  { id: "p13", scope: "plant" },
  { id: "p14", scope: "plant" },
  { id: "p15", scope: "plant" },
  { id: "p16", scope: "plant" },
  { id: "p17", scope: "plant" },
  { id: "p18", scope: "plant" },
  { id: "p19", scope: "plant" },
  { id: "p20", scope: "plant" },
  { id: "p21", scope: "plant" },
  { id: "p22", scope: "plant" },
  { id: "p23", scope: "plant" },
  { id: "p24", scope: "plant" },
  { id: "p25", scope: "plant" },
  { id: "p26", scope: "plant" },
  { id: "p27", scope: "plant" },
  { id: "p28", scope: "plant" },
  { id: "p29", scope: "plant" },
  { id: "p30", scope: "plant" },
  { id: "p31", scope: "plant" },
  { id: "p32", scope: "plant" },
  { id: "p33", scope: "plant" },
  { id: "p34", scope: "plant" },
  { id: "p35", scope: "plant" },
  { id: "p36", scope: "plant" },
  { id: "p37", scope: "plant" },
  { id: "p38", scope: "plant" },
  { id: "p39", scope: "plant" },
  { id: "p40", scope: "plant" },
  { id: "p41", scope: "plant" },
  { id: "p42", scope: "plant" },
  { id: "p43", scope: "plant" },
  { id: "p44", scope: "plant" },
  { id: "p45", scope: "plant" },
  { id: "p46", scope: "plant" },
  { id: "p47", scope: "plant" },
  { id: "p48", scope: "plant" },
  { id: "p49", scope: "plant" },
  { id: "p50", scope: "plant" },
  { id: "p51", scope: "plant" },
  { id: "p52", scope: "plant" },
  { id: "p53", scope: "plant" },
  { id: "p54", scope: "plant" },
  { id: "p55", scope: "plant" },
  { id: "p56", scope: "plant" },
  { id: "p57", scope: "plant" },
  { id: "p58", scope: "plant" },
  { id: "p59", scope: "plant" },
  { id: "p60", scope: "plant" },
  { id: "p61", scope: "plant" },
  { id: "p62", scope: "plant" },
  { id: "p63", scope: "plant" },
  { id: "p64", scope: "plant" },
  { id: "p65", scope: "plant" },
  { id: "p66", scope: "plant" },
  { id: "p67", scope: "plant" },
  { id: "p68", scope: "plant" },
  { id: "p69", scope: "plant" },
  { id: "p70", scope: "plant" },
  { id: "p71", scope: "plant" },
  { id: "p72", scope: "plant" },
  { id: "p73", scope: "plant" },
  { id: "p74", scope: "plant" },
  { id: "p75", scope: "plant" },
  { id: "p76", scope: "plant" },
  { id: "p77", scope: "plant" },
  { id: "p78", scope: "plant" },
  { id: "p79", scope: "plant" },
  { id: "p80", scope: "plant" },
  { id: "p81", scope: "plant" },
  { id: "p82", scope: "plant" },
  { id: "p83", scope: "plant" },
  { id: "p84", scope: "plant" },
  { id: "p85", scope: "plant" },
  { id: "p86", scope: "plant" },
  { id: "p87", scope: "plant" },
  { id: "p88", scope: "plant" },
  { id: "p89", scope: "plant" },
  { id: "p90", scope: "plant" },
  { id: "t1", scope: "plant", requires: "toxic" },
  { id: "t2", scope: "plant", requires: "toxic" },
  { id: "t3", scope: "plant", requires: "toxic" },
  { id: "t4", scope: "plant", requires: "toxic" },
  { id: "t5", scope: "plant", requires: "toxic" },
  { id: "o1", scope: "plant", requires: "overdue" },
  { id: "o2", scope: "plant", requires: "overdue" },
  { id: "o3", scope: "plant", requires: "overdue" },
  { id: "n1", scope: "plant", requires: "neverWatered" },
  { id: "n2", scope: "plant", requires: "neverWatered" },
  { id: "d1", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d2", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d3", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d4", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d5", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d6", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d7", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d8", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d9", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d10", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d11", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d12", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d13", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d14", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d15", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d16", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d17", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d18", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d19", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d20", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d21", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d22", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d23", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d24", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "d25", scope: "diagnosis", requires: "hasDiagnosis" },
  { id: "s1", scope: "species", needsSpecies: true },
  { id: "s2", scope: "species", needsSpecies: true },
  { id: "s3", scope: "species", needsSpecies: true },
  { id: "s4", scope: "species", needsSpecies: true },
  { id: "s5", scope: "species", needsSpecies: true },
  { id: "s6", scope: "species", needsSpecies: true },
  { id: "s7", scope: "species", needsSpecies: true },
  { id: "s8", scope: "species", needsSpecies: true },
  { id: "s9", scope: "species", needsSpecies: true },
  { id: "s10", scope: "species", needsSpecies: true },
  { id: "s11", scope: "species", needsSpecies: true },
  { id: "s12", scope: "species", needsSpecies: true },
  { id: "s13", scope: "species", needsSpecies: true },
  { id: "s14", scope: "species", needsSpecies: true },
  { id: "s15", scope: "species", needsSpecies: true },
  { id: "s16", scope: "species", needsSpecies: true },
  { id: "s17", scope: "species", needsSpecies: true },
  { id: "s18", scope: "species", needsSpecies: true },
  { id: "s19", scope: "species", needsSpecies: true },
  { id: "s20", scope: "species", needsSpecies: true },
  { id: "s21", scope: "species", needsSpecies: true },
  { id: "s22", scope: "species", needsSpecies: true },
  { id: "s23", scope: "species", needsSpecies: true },
  { id: "s24", scope: "species", needsSpecies: true },
  { id: "s25", scope: "species", needsSpecies: true },
  { id: "s26", scope: "species", needsSpecies: true },
  { id: "s27", scope: "species", needsSpecies: true },
  { id: "s28", scope: "species", needsSpecies: true },
  { id: "s29", scope: "species", needsSpecies: true },
  { id: "s30", scope: "species", needsSpecies: true },
  { id: "s31", scope: "species", needsSpecies: true },
  { id: "s32", scope: "species", needsSpecies: true },
  { id: "s33", scope: "species", needsSpecies: true },
  { id: "s34", scope: "species", needsSpecies: true },
  { id: "s35", scope: "species", needsSpecies: true },
  { id: "g1", scope: "general" },
  { id: "g2", scope: "general" },
  { id: "g3", scope: "general" },
  { id: "g4", scope: "general" },
  { id: "g5", scope: "general" },
  { id: "g6", scope: "general" },
  { id: "g7", scope: "general" },
  { id: "g8", scope: "general" },
  { id: "g9", scope: "general" },
  { id: "g10", scope: "general" },
  { id: "g11", scope: "general" },
  { id: "g12", scope: "general" },
  { id: "g13", scope: "general" },
  { id: "g14", scope: "general" },
  { id: "g15", scope: "general" },
  { id: "g16", scope: "general" },
  { id: "g17", scope: "general" },
  { id: "g18", scope: "general" },
  { id: "g19", scope: "general" },
  { id: "g20", scope: "general" },
  { id: "g21", scope: "general" },
  { id: "g22", scope: "general" },
  { id: "g23", scope: "general" },
  { id: "g24", scope: "general" },
  { id: "g25", scope: "general" },
  { id: "g26", scope: "general" },
  { id: "g27", scope: "general" },
  { id: "g28", scope: "general" },
  { id: "g29", scope: "general" },
  { id: "g30", scope: "general" },
  { id: "g31", scope: "general" },
  { id: "g32", scope: "general" },
  { id: "g33", scope: "general" },
  { id: "g34", scope: "general" },
  { id: "g35", scope: "general" },
  { id: "g36", scope: "general" },
  { id: "g37", scope: "general" },
  { id: "g38", scope: "general" },
  { id: "g39", scope: "general" },
  { id: "g40", scope: "general" },
  { id: "g41", scope: "general" },
  { id: "g42", scope: "general" },
  { id: "g43", scope: "general" },
  { id: "g44", scope: "general" },
];
