import { LanguageCode } from "@/constants/languages";

export interface QuizQuestion {
  ask: string;
  options: string[];
  answer: number;
  why: string;
}

export const QUIZ_ROUND = 8;

export const QUIZ: Record<LanguageCode, QuizQuestion[]> = {
  "pt-BR": [
    {
      ask: "Folha amarelando de baixo pra cima costuma ser sinal de quê?",
      options: ["Excesso de água", "Falta de sol", "Vaso pequeno"],
      answer: 0,
      why: "Raiz encharcada não respira, e a planta descarta as folhas velhas primeiro.",
    },
    {
      ask: "Qual o jeito mais confiável de saber se é hora de regar?",
      options: ["Contar os dias", "Enfiar o dedo na terra", "Olhar a folha"],
      answer: 1,
      why: "Três centímetros de dedo na terra dizem mais que qualquer calendário.",
    },
    {
      ask: "Vaso sem furo embaixo é problema?",
      options: ["Não, se regar pouco", "Sim, quase sempre", "Só no inverno"],
      answer: 1,
      why: "Sem dreno a água fica parada no fundo e apodrece a raiz.",
    },
    {
      ask: "Quando trocar a planta de vaso?",
      options: [
        "Todo ano, na data",
        "Quando a raiz sai pelo furo",
        "Quando a folha cai",
      ],
      answer: 1,
      why: "Raiz saindo pelo dreno ou enrolada no fundo é o sinal real.",
    },
    {
      ask: "Luz indireta significa o quê?",
      options: [
        "Claridade sem sol batendo na folha",
        "Sombra total",
        "Sol da manhã inteiro",
      ],
      answer: 0,
      why: "É o cômodo claro onde o raio de sol não encosta direto na planta.",
    },
    {
      ask: "Adubar uma planta doente ajuda a recuperar?",
      options: ["Ajuda sempre", "Costuma piorar", "Tanto faz"],
      answer: 1,
      why: "Raiz debilitada não absorve o sal do adubo, e ele queima ainda mais.",
    },
    {
      ask: "Pontinhas das folhas marrons e secas indicam o quê?",
      options: ["Ar seco ou rega irregular", "Excesso de adubo só", "Praga"],
      answer: 0,
      why: "Costuma ser ar seco, rega irregular ou água muito dura.",
    },
    {
      ask: "Onde ficam escondidos a cochonilha e o ácaro?",
      options: ["No caule", "Embaixo da folha", "Na flor"],
      answer: 1,
      why: "Por isso vale virar a folha antes de concluir qualquer diagnóstico.",
    },
    {
      ask: "Pratinho com água parada embaixo do vaso é bom?",
      options: ["Sim, mantém úmido", "Não, apodrece a raiz", "Só pra cacto"],
      answer: 1,
      why: "A raiz fica submersa e sem ar. Esvazie o pratinho depois de regar.",
    },
    {
      ask: "Melhor horário pra regar no calor?",
      options: ["Meio-dia", "De manhã cedo ou fim de tarde", "Tanto faz"],
      answer: 1,
      why: "No pico do sol boa parte evapora antes de chegar na raiz.",
    },
    {
      ask: "A planta esticou e ficou com folhas ralas. O que houve?",
      options: ["Falta de luz", "Excesso de adubo", "Vaso grande demais"],
      answer: 0,
      why: "Ela se estica procurando luz. Chama-se estiolamento.",
    },
    {
      ask: "Vaso muito maior que a planta ajuda a crescer mais rápido?",
      options: ["Sim, sempre", "Não, atrapalha", "Só pra suculenta"],
      answer: 1,
      why: "Terra demais segura água demais em volta de uma raiz pequena.",
    },
    {
      ask: "Cacto e suculenta precisam de qual terra?",
      options: ["Terra comum", "Substrato que drena rápido", "Só areia"],
      answer: 1,
      why: "Mistura com areia grossa ou perlita, pra água não ficar parada.",
    },
    {
      ask: "Com que frequência se aduba planta de vaso na primavera?",
      options: [
        "Toda semana",
        "Mais ou menos uma vez por mês",
        "Uma vez por ano",
      ],
      answer: 1,
      why: "Na estação de crescimento, mensal costuma bastar. No inverno, quase nada.",
    },
    {
      ask: "Mosquinha preta rodeando a terra indica o quê?",
      options: ["Terra encharcada", "Falta de adubo", "Sol demais"],
      answer: 0,
      why: "É o fungus gnat. Ele se reproduz em terra sempre úmida.",
    },
    {
      ask: "Posso podar folha seca a qualquer momento?",
      options: ["Sim", "Só no inverno", "Nunca"],
      answer: 0,
      why: "Folha seca não volta. Cortar libera energia pro resto da planta.",
    },
    {
      ask: "Planta recém-comprada deve ser replantada na hora?",
      options: ["Sim, sempre", "Melhor esperar umas semanas", "Nunca"],
      answer: 1,
      why: "Ela já está estressada pela mudança. Deixe se adaptar antes.",
    },
    {
      ask: "Folha com pó branco parecendo farinha é o quê?",
      options: ["Poeira", "Oídio, um fungo", "Falta de água"],
      answer: 1,
      why: "Fungo de ar parado e úmido. Melhore a ventilação e isole a planta.",
    },
    {
      ask: "O que fazer com uma planta que vai ficar 15 dias sozinha?",
      options: [
        "Encher o pratinho",
        "Regar bem antes e tirar do sol direto",
        "Não regar",
      ],
      answer: 1,
      why: "Rega boa, longe do sol forte, reduz a perda de água pela folha.",
    },
    {
      ask: "Água da torneira serve pra regar?",
      options: ["Quase sempre serve", "Nunca serve", "Só filtrada"],
      answer: 0,
      why: "Na maioria dos casos serve. Se a água for muito dura, deixe descansar.",
    },
    {
      ask: "Folha amarela que cai sozinha na base é sempre problema?",
      options: ["Sim", "Nem sempre, pode ser folha velha", "Só no verão"],
      answer: 1,
      why: "Planta descarta folha velha naturalmente. Preocupe-se se forem várias.",
    },
    {
      ask: "Girar o vaso de vez em quando serve pra quê?",
      options: ["Nada", "Crescer parelho, não torto pra luz", "Espantar praga"],
      answer: 1,
      why: "Sem girar, ela cresce inclinada na direção da janela.",
    },
    {
      ask: "Limpar o pó das folhas faz diferença?",
      options: [
        "Faz, ela respira e capta luz melhor",
        "Não faz",
        "Só em planta grande",
      ],
      answer: 0,
      why: "Pó bloqueia luz e entope os poros da folha. Pano úmido resolve.",
    },
    {
      ask: "Posso usar óleo de cozinha pra dar brilho na folha?",
      options: ["Sim", "Não, entope a folha", "Só uma gota"],
      answer: 1,
      why: "Óleo fecha os estômatos e a folha para de respirar direito.",
    },
    {
      ask: "A planta murchou mesmo com a terra molhada. O que pode ser?",
      options: ["Raiz apodrecida", "Falta de água", "Sol de menos"],
      answer: 0,
      why: "Raiz podre não puxa água, então a planta murcha nadando.",
    },
    {
      ask: "Quando é melhor trocar de vaso?",
      options: ["Fim do outono", "Começo da primavera", "Meio do inverno"],
      answer: 1,
      why: "Ela está entrando em crescimento e se recupera mais rápido.",
    },
    {
      ask: "Folha nova pequena e deformada costuma indicar o quê?",
      options: [
        "Falta de nutriente ou praga sugando",
        "Excesso de luz",
        "Vaso novo",
      ],
      answer: 0,
      why: "Vale olhar embaixo da folha nova antes de adubar.",
    },
    {
      ask: "Planta de banheiro sem janela: dá certo?",
      options: ["Sempre", "Só espécie que aguenta pouca luz", "Nunca"],
      answer: 1,
      why: "Sem luz nenhuma não existe planta que viva. Precisa de alguma claridade.",
    },
    {
      ask: "Borrifar água na folha substitui a rega?",
      options: ["Sim", "Não, é só umidade do ar", "Só no inverno"],
      answer: 1,
      why: "A planta bebe pela raiz. Borrifar ajuda no ar seco, não alimenta.",
    },
    {
      ask: "Terra que virou uma pedra dura e a água escorre pelo lado. E agora?",
      options: ["Regar mais", "Afofar ou trocar o substrato", "Adubar"],
      answer: 1,
      why: "Compactada, ela repele água. A raiz fica sem beber mesmo molhando.",
    },
    {
      ask: "Sol direto da tarde no verão é bom pra maioria das plantas de casa?",
      options: ["Sim", "Não, costuma queimar a folha", "Só pra samambaia"],
      answer: 1,
      why: "Planta de interior evoluiu sob copas. O sol das 14h queima.",
    },
    {
      ask: "Mancha marrom com halo amarelo ao redor sugere o quê?",
      options: ["Fungo ou bactéria", "Falta de água", "Excesso de luz"],
      answer: 0,
      why: "Halo amarelo em volta da mancha é sinal clássico de infecção.",
    },
    {
      ask: "Posso plantar várias mudas juntas no mesmo vaso?",
      options: [
        "Sim, se tiverem cuidados parecidos",
        "Nunca",
        "Só se forem iguais",
      ],
      answer: 0,
      why: "O problema é juntar uma que quer água toda semana com um cacto.",
    },
    {
      ask: "Raiz aparecendo na superfície da terra é problema?",
      options: [
        "Sinal de que o vaso ficou pequeno",
        "Normal sempre",
        "Falta de adubo",
      ],
      answer: 0,
      why: "Junto com raiz saindo pelo dreno, é o sinal de trocar de vaso.",
    },
    {
      ask: "Depois de trocar de vaso, quando adubar?",
      options: ["No mesmo dia", "Depois de umas quatro semanas", "Nunca mais"],
      answer: 1,
      why: "O substrato novo já traz nutriente, e a raiz mexida queima fácil.",
    },
    {
      ask: "Folhas caindo de repente depois de mudar a planta de lugar.",
      options: [
        "Ela está morrendo",
        "Estresse de mudança, costuma passar",
        "Falta de adubo",
      ],
      answer: 1,
      why: "Muita planta reage à mudança de luz soltando folha. Dê tempo.",
    },
    {
      ask: "Enraizar muda na água ou direto na terra?",
      options: ["Água é mais fácil de acompanhar", "Terra sempre", "Tanto faz"],
      answer: 0,
      why: "Na água você vê a raiz nascer. Depois passe pra terra antes dela ficar grande.",
    },
    {
      ask: "Vaso de barro ou de plástico segura mais água?",
      options: ["Barro", "Plástico", "Igual"],
      answer: 1,
      why: "O barro é poroso e evapora pelos lados. Bom pra quem rega demais.",
    },
    {
      ask: "Regar por baixo, colocando o vaso na água, funciona?",
      options: ["Sim, por 15 a 30 minutos", "Não, afoga", "Só pra cacto"],
      answer: 0,
      why: "A terra puxa por capilaridade. Tire o vaso quando a superfície umedecer.",
    },
    {
      ask: "Casca de ovo na terra vira cálcio rápido?",
      options: ["Sim, na hora", "Não, demora muito a decompor", "Nunca vira"],
      answer: 1,
      why: "Leva meses. Não é solução pra planta que precisa de nutriente agora.",
    },
    {
      ask: "O que significam os três números do adubo, tipo 10-10-10?",
      options: [
        "Nitrogênio, fósforo e potássio",
        "Peso, volume e preço",
        "Dias de efeito",
      ],
      answer: 0,
      why: "N faz folha, P faz raiz e flor, K deixa a planta resistente.",
    },
    {
      ask: "Planta que perde todas as folhas no inverno está morta?",
      options: ["Sempre", "Pode estar dormente", "Só se for cacto"],
      answer: 1,
      why: "Muita espécie entra em dormência. Raspe o caule: verde por dentro é vida.",
    },
    {
      ask: "Cortar a flor murcha faz diferença?",
      options: ["Faz, estimula flor nova", "Não faz", "Atrapalha"],
      answer: 0,
      why: "Sem semente pra alimentar, a planta reinveste em florescer de novo.",
    },
    {
      ask: "Cochonilha algodãozinha branca: primeiro passo?",
      options: ["Isolar a planta das outras", "Adubar", "Regar mais"],
      answer: 0,
      why: "Ela anda pra planta vizinha. Isolar antes de tratar evita virar epidemia.",
    },
    {
      ask: "Folha com riscos prateados e pontinhos pretos indica o quê?",
      options: ["Tripes", "Falta de água", "Sol demais"],
      answer: 0,
      why: "O prateado é a célula vazia depois que o bicho sugou.",
    },
    {
      ask: "Mosca branca some sozinha?",
      options: ["Sim", "Não, ela se multiplica rápido", "Só no inverno"],
      answer: 1,
      why: "Cada fêmea põe centenas de ovos. Quanto antes tratar, menos trabalho.",
    },
    {
      ask: "Planta comprada com terra encharcada da loja: o que fazer?",
      options: ["Regar de novo", "Deixar secar e conferir a raiz", "Adubar"],
      answer: 1,
      why: "Loja costuma regar demais. Raiz marrom e mole já é podridão.",
    },
    {
      ask: "Colocar pedra no fundo do vaso melhora a drenagem?",
      options: ["Melhora muito", "É mito, pode piorar", "Só em vaso grande"],
      answer: 1,
      why: "Cria uma camada onde a água empoça. O que resolve é furo e substrato bom.",
    },
    {
      ask: "Qual sinal de que a planta quer mais luz?",
      options: [
        "Folha nova pequena e caule esticado",
        "Folha queimada",
        "Terra seca rápido",
      ],
      answer: 0,
      why: "Ela alonga o caule e diminui a folha pra chegar mais perto da luz.",
    },
    {
      ask: "E de que está com luz demais?",
      options: [
        "Folha desbotada ou com mancha seca clara",
        "Folha escura",
        "Caule fino",
      ],
      answer: 0,
      why: "Queimadura de sol clareia e resseca em mancha, sem halo amarelo.",
    },
    {
      ask: "Umidade do ar: como aumentar de verdade?",
      options: [
        "Borrifar de vez em quando",
        "Agrupar plantas ou usar bandeja com pedra e água",
        "Fechar a janela",
      ],
      answer: 1,
      why: "Borrifar sobe a umidade por poucos minutos. Agrupar mantém.",
    },
    {
      ask: "Ar-condicionado atrapalha planta?",
      options: ["Sim, resseca o ar", "Não muda nada", "Ajuda"],
      answer: 0,
      why: "Ele tira umidade do ambiente. Evite o vento direto na folha.",
    },
    {
      ask: "Quando a raiz está enrolada em novelo, o que fazer no replantio?",
      options: ["Soltar e afrouxar as raízes", "Não mexer", "Cortar tudo"],
      answer: 0,
      why: "Se não afrouxar, ela continua crescendo em círculo no vaso novo.",
    },
    {
      ask: "Substrato com muita perlita serve pra quê?",
      options: ["Deixar entrar ar e drenar", "Segurar mais água", "Adubar"],
      answer: 0,
      why: "As bolinhas brancas criam espaço de ar entre a terra.",
    },
    {
      ask: "Café coado usado na terra: pode?",
      options: [
        "Pode, em pouca quantidade e misturado",
        "Todo dia, puro",
        "Nunca",
      ],
      answer: 0,
      why: "Em excesso ele compacta e mofa. Melhor na composteira.",
    },
    {
      ask: "Orquídea vive em terra comum?",
      options: [
        "Sim",
        "Não, precisa de casca ou substrato arejado",
        "Só a branca",
      ],
      answer: 1,
      why: "A raiz dela é aérea e apodrece em terra fechada.",
    },
    {
      ask: "Quando regar orquídea?",
      options: [
        "Quando a raiz fica esbranquiçada",
        "Todo dia",
        "Uma vez por mês fixo",
      ],
      answer: 0,
      why: "Raiz verde é raiz hidratada. Esbranquiçada pede água.",
    },
    {
      ask: "Planta tóxica pra pet dentro de casa: melhor conduta?",
      options: [
        "Deixar fora do alcance e consultar veterinário na dúvida",
        "Sempre descartar",
        "Ignorar",
      ],
      answer: 0,
      why: "Altura e cômodo fechado resolvem a maioria dos casos.",
    },
    {
      ask: "Samambaia gosta de quê?",
      options: ["Sombra com umidade", "Sol pleno", "Terra seca"],
      answer: 0,
      why: "Ela vem do chão de mata: luz filtrada e ar úmido.",
    },
    {
      ask: "Suculenta enrugada e murcha significa o quê?",
      options: ["Sede", "Excesso de água", "Falta de adubo"],
      answer: 0,
      why: "Ela usa a própria reserva. Enrugou pra dentro, é hora de regar.",
    },
    {
      ask: "Suculenta com folha mole, translúcida e amarelada?",
      options: ["Excesso de água", "Sede", "Frio"],
      answer: 0,
      why: "A célula estourou de tanta água. Essa folha não volta.",
    },
    {
      ask: "Qual a melhor tesoura pra podar?",
      options: [
        "Qualquer uma",
        "Limpa e afiada",
        "Sem fio, pra não cortar demais",
      ],
      answer: 1,
      why: "Corte limpo cicatriza rápido. Lâmina suja transmite doença entre plantas.",
    },
    {
      ask: "Precisa esterilizar a tesoura entre uma planta e outra?",
      options: [
        "Sim, principalmente se uma estiver doente",
        "Nunca",
        "Só no inverno",
      ],
      answer: 0,
      why: "Álcool na lâmina evita levar fungo de uma pra outra.",
    },
    {
      ask: "Mudança de folhagem ao trocar de estação é normal?",
      options: ["Sim, muitas plantas ajustam", "Nunca", "Só em planta doente"],
      answer: 0,
      why: "Menos luz no inverno significa menos folha. Ela volta na primavera.",
    },
    {
      ask: "Terra com mofo branco na superfície: grave?",
      options: [
        "Costuma ser excesso de umidade e pouca ventilação",
        "Sempre mata a planta",
        "É adubo",
      ],
      answer: 0,
      why: "Raspe a camada, deixe secar mais entre regas e melhore o ar.",
    },
    {
      ask: "Planta na varanda com vento forte o dia todo?",
      options: [
        "Tudo bem sempre",
        "Vento resseca e rasga folha",
        "Ajuda a crescer",
      ],
      answer: 1,
      why: "Vento constante aumenta a perda de água e quebra folha grande.",
    },
    {
      ask: "Adubo de liberação lenta serve pra quê?",
      options: [
        "Alimentar aos poucos por meses",
        "Efeito imediato",
        "Matar praga",
      ],
      answer: 0,
      why: "As bolinhas liberam nutriente a cada rega. Menos risco de queimar.",
    },
    {
      ask: "Sal de Epsom resolve qualquer problema da planta?",
      options: ["Sim", "Não, só ajuda em falta de magnésio", "Nunca serve"],
      answer: 1,
      why: "É magnésio. Usar sem necessidade só acumula sal na terra.",
    },
  ],
  "en-US": [
    {
      ask: "Leaves yellowing from the bottom up usually mean what?",
      options: ["Too much water", "Not enough sun", "Pot too small"],
      answer: 0,
      why: "Waterlogged roots cannot breathe, so the plant drops old leaves first.",
    },
    {
      ask: "What is the most reliable way to know it is time to water?",
      options: [
        "Count the days",
        "Push a finger into the soil",
        "Look at a leaf",
      ],
      answer: 1,
      why: "Three centimetres of finger in the soil beats any calendar.",
    },
    {
      ask: "Is a pot without a drainage hole a problem?",
      options: [
        "No, if you water little",
        "Yes, almost always",
        "Only in winter",
      ],
      answer: 1,
      why: "With no drainage the water sits at the bottom and rots the roots.",
    },
    {
      ask: "When should you repot?",
      options: [
        "Every year, on a date",
        "When roots come out of the hole",
        "When a leaf falls",
      ],
      answer: 1,
      why: "Roots escaping the drainage hole or circling the bottom is the real sign.",
    },
    {
      ask: "What does indirect light mean?",
      options: [
        "Brightness with no sun touching the leaf",
        "Full shade",
        "A whole morning of sun",
      ],
      answer: 0,
      why: "A bright room where the sunbeam never lands on the plant itself.",
    },
    {
      ask: "Does fertilising a sick plant help it recover?",
      options: [
        "Always helps",
        "Usually makes it worse",
        "Makes no difference",
      ],
      answer: 1,
      why: "Weak roots cannot take up the salts, so the fertiliser burns them further.",
    },
    {
      ask: "Brown, dry leaf tips point to what?",
      options: [
        "Dry air or uneven watering",
        "Only excess fertiliser",
        "Pests",
      ],
      answer: 0,
      why: "Usually dry air, irregular watering or very hard water.",
    },
    {
      ask: "Where do mealybugs and mites hide?",
      options: ["On the stem", "Under the leaf", "In the flower"],
      answer: 1,
      why: "That is why turning a leaf over matters before any diagnosis.",
    },
    {
      ask: "Is standing water in the saucer a good thing?",
      options: [
        "Yes, keeps it moist",
        "No, it rots the roots",
        "Only for cacti",
      ],
      answer: 1,
      why: "Roots sit submerged with no air. Empty the saucer after watering.",
    },
    {
      ask: "Best time to water in hot weather?",
      options: ["Midday", "Early morning or late afternoon", "Does not matter"],
      answer: 1,
      why: "At peak sun much of it evaporates before reaching the roots.",
    },
    {
      ask: "The plant stretched out with sparse leaves. What happened?",
      options: ["Not enough light", "Too much fertiliser", "Pot too big"],
      answer: 0,
      why: "It stretches looking for light. That is etiolation.",
    },
    {
      ask: "Does a much bigger pot make a plant grow faster?",
      options: ["Yes, always", "No, it backfires", "Only for succulents"],
      answer: 1,
      why: "Too much soil holds too much water around a small root ball.",
    },
    {
      ask: "What soil do cacti and succulents need?",
      options: ["Regular soil", "A fast draining mix", "Sand only"],
      answer: 1,
      why: "Mixed with coarse sand or perlite so water never sits.",
    },
    {
      ask: "How often do you feed a potted plant in spring?",
      options: ["Every week", "Roughly once a month", "Once a year"],
      answer: 1,
      why: "Monthly is usually enough in the growing season. Almost none in winter.",
    },
    {
      ask: "Tiny black flies around the soil mean what?",
      options: ["Soil kept too wet", "Lack of fertiliser", "Too much sun"],
      answer: 0,
      why: "Fungus gnats. They breed in permanently damp soil.",
    },
    {
      ask: "Can I cut off a dry leaf any time?",
      options: ["Yes", "Only in winter", "Never"],
      answer: 0,
      why: "A dry leaf never comes back. Cutting frees energy for the rest.",
    },
    {
      ask: "Should a newly bought plant be repotted right away?",
      options: ["Yes, always", "Better to wait a few weeks", "Never"],
      answer: 1,
      why: "It is already stressed by the move. Let it settle first.",
    },
    {
      ask: "A white flour-like dust on the leaf is what?",
      options: ["Dust", "Powdery mildew, a fungus", "Thirst"],
      answer: 1,
      why: "A fungus of still, humid air. Improve airflow and isolate the plant.",
    },
    {
      ask: "What to do with a plant left alone for 15 days?",
      options: [
        "Fill the saucer",
        "Water well and move it out of direct sun",
        "Do not water",
      ],
      answer: 1,
      why: "A good soak away from strong sun cuts water loss through the leaves.",
    },
    {
      ask: "Is tap water fine for watering?",
      options: ["Usually fine", "Never fine", "Only filtered"],
      answer: 0,
      why: "In most cases it is fine. If your water is very hard, let it rest first.",
    },
    {
      ask: "Is a yellow leaf falling at the base always a problem?",
      options: ["Yes", "Not always, it may be an old leaf", "Only in summer"],
      answer: 1,
      why: "Plants shed old leaves naturally. Worry when several go at once.",
    },
    {
      ask: "Why rotate the pot now and then?",
      options: [
        "No reason",
        "So it grows even, not leaning at the light",
        "To scare pests",
      ],
      answer: 1,
      why: "Without rotating it grows tilted towards the window.",
    },
    {
      ask: "Does wiping dust off leaves matter?",
      options: [
        "Yes, it breathes and catches light better",
        "No",
        "Only on big plants",
      ],
      answer: 0,
      why: "Dust blocks light and clogs the leaf pores. A damp cloth does it.",
    },
    {
      ask: "Can I use cooking oil to shine the leaves?",
      options: ["Yes", "No, it clogs the leaf", "Just a drop"],
      answer: 1,
      why: "Oil seals the stomata and the leaf stops breathing properly.",
    },
    {
      ask: "The plant wilted even with wet soil. What could it be?",
      options: ["Rotten roots", "Thirst", "Not enough sun"],
      answer: 0,
      why: "Rotten roots cannot pull water, so it wilts while swimming.",
    },
    {
      ask: "When is the best time to repot?",
      options: ["Late autumn", "Early spring", "Midwinter"],
      answer: 1,
      why: "It is entering growth and recovers much faster.",
    },
    {
      ask: "Small, deformed new leaves usually point to what?",
      options: [
        "Missing nutrient or a sucking pest",
        "Too much light",
        "A new pot",
      ],
      answer: 0,
      why: "Worth checking under the new leaves before you feed it.",
    },
    {
      ask: "A windowless bathroom plant: does it work?",
      options: ["Always", "Only species that take low light", "Never"],
      answer: 1,
      why: "With no light at all nothing survives. It needs some brightness.",
    },
    {
      ask: "Does misting the leaves replace watering?",
      options: ["Yes", "No, it is only air humidity", "Only in winter"],
      answer: 1,
      why: "Plants drink through roots. Misting helps dry air, it does not feed.",
    },
    {
      ask: "The soil turned rock hard and water runs down the side. Now what?",
      options: ["Water more", "Loosen or replace the mix", "Fertilise"],
      answer: 1,
      why: "Compacted soil repels water. The root stays thirsty while you soak it.",
    },
    {
      ask: "Is direct afternoon summer sun good for most houseplants?",
      options: ["Yes", "No, it usually burns the leaf", "Only for ferns"],
      answer: 1,
      why: "Houseplants evolved under canopies. The 2pm sun scorches them.",
    },
    {
      ask: "A brown spot with a yellow halo around it suggests what?",
      options: ["Fungus or bacteria", "Thirst", "Too much light"],
      answer: 0,
      why: "A yellow halo around the spot is a classic sign of infection.",
    },
    {
      ask: "Can I plant several cuttings in the same pot?",
      options: ["Yes, if their care matches", "Never", "Only identical ones"],
      answer: 0,
      why: "The problem is pairing a weekly drinker with a cactus.",
    },
    {
      ask: "Roots showing on the soil surface: a problem?",
      options: [
        "A sign the pot got small",
        "Always normal",
        "Lack of fertiliser",
      ],
      answer: 0,
      why: "Along with roots out of the drainage hole, it is the repotting sign.",
    },
    {
      ask: "After repotting, when should you fertilise?",
      options: ["Same day", "After about four weeks", "Never again"],
      answer: 1,
      why: "Fresh mix already carries nutrients, and disturbed roots burn easily.",
    },
    {
      ask: "Leaves dropping suddenly after moving the plant.",
      options: [
        "It is dying",
        "Move stress, usually passes",
        "Lack of fertiliser",
      ],
      answer: 1,
      why: "Many plants react to a light change by shedding leaves. Give it time.",
    },
    {
      ask: "Root a cutting in water or straight into soil?",
      options: ["Water is easier to watch", "Soil always", "Either way"],
      answer: 0,
      why: "In water you see roots appear. Move to soil before they get long.",
    },
    {
      ask: "Which holds water longer, terracotta or plastic?",
      options: ["Terracotta", "Plastic", "The same"],
      answer: 1,
      why: "Terracotta is porous and evaporates through the sides. Good for overwaterers.",
    },
    {
      ask: "Does bottom watering, standing the pot in water, work?",
      options: [
        "Yes, for 15 to 30 minutes",
        "No, it drowns the plant",
        "Only for cacti",
      ],
      answer: 0,
      why: "Soil wicks it up. Remove the pot once the surface turns damp.",
    },
    {
      ask: "Do eggshells turn into calcium quickly?",
      options: [
        "Yes, right away",
        "No, they take ages to break down",
        "Never do",
      ],
      answer: 1,
      why: "It takes months. Not a fix for a plant that needs nutrients now.",
    },
    {
      ask: "What do the three fertiliser numbers, like 10-10-10, mean?",
      options: [
        "Nitrogen, phosphorus and potassium",
        "Weight, volume and price",
        "Days of effect",
      ],
      answer: 0,
      why: "N builds leaves, P roots and flowers, K overall resilience.",
    },
    {
      ask: "Is a plant that drops every leaf in winter dead?",
      options: ["Always", "It may be dormant", "Only if it is a cactus"],
      answer: 1,
      why: "Many species go dormant. Scratch the stem: green inside means alive.",
    },
    {
      ask: "Does removing a spent flower make a difference?",
      options: ["Yes, it encourages new blooms", "No", "It hurts"],
      answer: 0,
      why: "With no seed to feed, the plant reinvests in flowering again.",
    },
    {
      ask: "Cottony white mealybugs: first step?",
      options: ["Isolate the plant from the others", "Fertilise", "Water more"],
      answer: 0,
      why: "They walk to the neighbouring pot. Isolate before treating.",
    },
    {
      ask: "Silvery streaks with tiny black dots point to what?",
      options: ["Thrips", "Thirst", "Too much sun"],
      answer: 0,
      why: "The silver is the emptied cell after the insect fed on it.",
    },
    {
      ask: "Do whiteflies go away on their own?",
      options: ["Yes", "No, they multiply fast", "Only in winter"],
      answer: 1,
      why: "Each female lays hundreds of eggs. Treat early, work less.",
    },
    {
      ask: "A shop plant arrives with soaking soil. What now?",
      options: ["Water again", "Let it dry and check the roots", "Fertilise"],
      answer: 1,
      why: "Shops overwater. Brown mushy roots already mean rot.",
    },
    {
      ask: "Do stones at the bottom of the pot improve drainage?",
      options: [
        "Greatly",
        "It is a myth, it can make it worse",
        "Only in big pots",
      ],
      answer: 1,
      why: "It creates a layer where water pools. A hole and good mix is the fix.",
    },
    {
      ask: "What tells you a plant wants more light?",
      options: [
        "Small new leaves and a stretched stem",
        "Burnt leaves",
        "Soil drying fast",
      ],
      answer: 0,
      why: "It lengthens the stem and shrinks leaves to get closer to light.",
    },
    {
      ask: "And that it is getting too much?",
      options: ["Faded leaves or pale dry patches", "Dark leaves", "Thin stem"],
      answer: 0,
      why: "Sunburn bleaches and dries into a patch, with no yellow halo.",
    },
    {
      ask: "Air humidity: how do you actually raise it?",
      options: [
        "Mist now and then",
        "Group plants or use a pebble tray",
        "Close the window",
      ],
      answer: 1,
      why: "Misting lifts humidity for minutes. Grouping sustains it.",
    },
    {
      ask: "Does air conditioning bother plants?",
      options: ["Yes, it dries the air", "No difference", "It helps"],
      answer: 0,
      why: "It pulls humidity out. Keep leaves out of the direct draught.",
    },
    {
      ask: "Roots circling in a tight ball: what do you do when repotting?",
      options: [
        "Loosen and tease the roots apart",
        "Leave them",
        "Cut them all off",
      ],
      answer: 0,
      why: "If you do not loosen them, they keep circling in the new pot.",
    },
    {
      ask: "What is perlite in a mix for?",
      options: ["Letting air in and draining", "Holding more water", "Feeding"],
      answer: 0,
      why: "The white beads create air pockets between soil particles.",
    },
    {
      ask: "Used coffee grounds on the soil: allowed?",
      options: ["Yes, small amounts, mixed in", "Every day, straight", "Never"],
      answer: 0,
      why: "Too much compacts and moulds. Better in the compost bin.",
    },
    {
      ask: "Do orchids live in regular soil?",
      options: ["Yes", "No, they need bark or an airy mix", "Only white ones"],
      answer: 1,
      why: "Their roots are aerial and rot in dense soil.",
    },
    {
      ask: "When should you water an orchid?",
      options: [
        "When the roots turn whitish",
        "Every day",
        "Once a month, fixed",
      ],
      answer: 0,
      why: "Green roots are hydrated roots. Whitish ones are asking.",
    },
    {
      ask: "A pet-toxic plant indoors: best approach?",
      options: [
        "Keep it out of reach and ask a vet if in doubt",
        "Always get rid of it",
        "Ignore it",
      ],
      answer: 0,
      why: "Height and a closed room solve most cases.",
    },
    {
      ask: "What do ferns like?",
      options: ["Shade with humidity", "Full sun", "Dry soil"],
      answer: 0,
      why: "They come from the forest floor: filtered light and damp air.",
    },
    {
      ask: "A wrinkled, shrivelled succulent means what?",
      options: ["Thirst", "Too much water", "Lack of fertiliser"],
      answer: 0,
      why: "It is living off its own reserve. Wrinkling inward means water it.",
    },
    {
      ask: "A succulent leaf that is soft, translucent and yellowing?",
      options: ["Too much water", "Thirst", "Cold"],
      answer: 0,
      why: "The cells burst from excess water. That leaf will not recover.",
    },
    {
      ask: "What is the best pruning tool?",
      options: ["Any one", "Clean and sharp", "Blunt, so you cut less"],
      answer: 1,
      why: "A clean cut heals fast. A dirty blade spreads disease between plants.",
    },
    {
      ask: "Should you sterilise the blade between plants?",
      options: ["Yes, especially if one is sick", "Never", "Only in winter"],
      answer: 0,
      why: "Alcohol on the blade stops you carrying fungus from one to another.",
    },
    {
      ask: "Is a change of foliage between seasons normal?",
      options: ["Yes, many plants adjust", "Never", "Only on sick plants"],
      answer: 0,
      why: "Less winter light means fewer leaves. They return in spring.",
    },
    {
      ask: "White mould on the soil surface: serious?",
      options: [
        "Usually too much moisture and poor airflow",
        "It always kills the plant",
        "It is fertiliser",
      ],
      answer: 0,
      why: "Scrape the layer, let it dry more between waterings, improve airflow.",
    },
    {
      ask: "A balcony plant in strong wind all day?",
      options: [
        "Always fine",
        "Wind dries and tears leaves",
        "It helps it grow",
      ],
      answer: 1,
      why: "Constant wind raises water loss and shreds large leaves.",
    },
    {
      ask: "What is slow release fertiliser for?",
      options: [
        "Feeding a little at a time for months",
        "Immediate effect",
        "Killing pests",
      ],
      answer: 0,
      why: "The beads release with each watering. Much less risk of burning.",
    },
    {
      ask: "Does Epsom salt fix any plant problem?",
      options: ["Yes", "No, only a magnesium shortage", "Never useful"],
      answer: 1,
      why: "It is magnesium. Using it without need just builds up salt in the soil.",
    },
  ],
  "es-ES": [
    {
      ask: "Hojas amarilleando de abajo hacia arriba suelen indicar qué?",
      options: ["Exceso de agua", "Falta de sol", "Maceta pequeña"],
      answer: 0,
      why: "La raíz encharcada no respira, y la planta suelta primero las hojas viejas.",
    },
    {
      ask: "¿Cuál es la forma más fiable de saber si toca regar?",
      options: [
        "Contar los días",
        "Meter el dedo en la tierra",
        "Mirar la hoja",
      ],
      answer: 1,
      why: "Tres centímetros de dedo en la tierra dicen más que cualquier calendario.",
    },
    {
      ask: "¿Una maceta sin agujero es un problema?",
      options: ["No, si riegas poco", "Sí, casi siempre", "Solo en invierno"],
      answer: 1,
      why: "Sin drenaje el agua se queda en el fondo y pudre la raíz.",
    },
    {
      ask: "¿Cuándo cambiar la planta de maceta?",
      options: [
        "Cada año, en una fecha",
        "Cuando la raíz sale por el agujero",
        "Cuando cae una hoja",
      ],
      answer: 1,
      why: "La raíz saliendo por el drenaje o enrollada en el fondo es la señal real.",
    },
    {
      ask: "¿Qué significa luz indirecta?",
      options: [
        "Claridad sin sol tocando la hoja",
        "Sombra total",
        "Toda la mañana de sol",
      ],
      answer: 0,
      why: "Es la habitación clara donde el rayo de sol no toca la planta.",
    },
    {
      ask: "¿Abonar una planta enferma ayuda a recuperarla?",
      options: ["Ayuda siempre", "Suele empeorarla", "Da igual"],
      answer: 1,
      why: "La raíz débil no absorbe las sales del abono, y este la quema más.",
    },
    {
      ask: "¿Puntas de hoja marrones y secas indican qué?",
      options: ["Aire seco o riego irregular", "Solo exceso de abono", "Plaga"],
      answer: 0,
      why: "Suele ser aire seco, riego irregular o agua muy dura.",
    },
    {
      ask: "¿Dónde se esconden la cochinilla y la araña roja?",
      options: ["En el tallo", "Debajo de la hoja", "En la flor"],
      answer: 1,
      why: "Por eso conviene girar una hoja antes de concluir cualquier diagnóstico.",
    },
    {
      ask: "¿Es bueno dejar agua en el plato bajo la maceta?",
      options: ["Sí, mantiene húmedo", "No, pudre la raíz", "Solo para cactus"],
      answer: 1,
      why: "La raíz queda sumergida y sin aire. Vacía el plato tras regar.",
    },
    {
      ask: "¿Mejor hora para regar con calor?",
      options: ["Mediodía", "Temprano o al atardecer", "Da igual"],
      answer: 1,
      why: "En pleno sol gran parte se evapora antes de llegar a la raíz.",
    },
    {
      ask: "La planta se estiró con hojas ralas. ¿Qué pasó?",
      options: ["Falta de luz", "Exceso de abono", "Maceta muy grande"],
      answer: 0,
      why: "Se estira buscando luz. Se llama ahilamiento.",
    },
    {
      ask: "¿Una maceta mucho más grande hace crecer más rápido?",
      options: ["Sí, siempre", "No, perjudica", "Solo suculentas"],
      answer: 1,
      why: "Demasiada tierra retiene demasiada agua alrededor de una raíz pequeña.",
    },
    {
      ask: "¿Qué sustrato necesitan cactus y suculentas?",
      options: ["Tierra común", "Sustrato de drenaje rápido", "Solo arena"],
      answer: 1,
      why: "Mezcla con arena gruesa o perlita, para que el agua no se quede.",
    },
    {
      ask: "¿Cada cuánto se abona una planta en maceta en primavera?",
      options: ["Cada semana", "Más o menos una vez al mes", "Una vez al año"],
      answer: 1,
      why: "En la estación de crecimiento, mensual basta. En invierno, casi nada.",
    },
    {
      ask: "¿Mosquitas negras rondando la tierra indican qué?",
      options: ["Tierra encharcada", "Falta de abono", "Demasiado sol"],
      answer: 0,
      why: "Es el mosquito del sustrato. Se reproduce en tierra siempre húmeda.",
    },
    {
      ask: "¿Puedo podar una hoja seca en cualquier momento?",
      options: ["Sí", "Solo en invierno", "Nunca"],
      answer: 0,
      why: "La hoja seca no vuelve. Cortarla libera energía para el resto.",
    },
    {
      ask: "¿Una planta recién comprada se trasplanta enseguida?",
      options: ["Sí, siempre", "Mejor esperar unas semanas", "Nunca"],
      answer: 1,
      why: "Ya viene estresada por el cambio. Deja que se adapte.",
    },
    {
      ask: "¿Un polvo blanco tipo harina en la hoja es qué?",
      options: ["Polvo", "Oídio, un hongo", "Sed"],
      answer: 1,
      why: "Hongo de aire quieto y húmedo. Mejora la ventilación y aísla la planta.",
    },
    {
      ask: "¿Qué hacer con una planta que queda sola 15 días?",
      options: [
        "Llenar el plato",
        "Regar bien y sacarla del sol directo",
        "No regar",
      ],
      answer: 1,
      why: "Un buen riego lejos del sol fuerte reduce la pérdida por la hoja.",
    },
    {
      ask: "¿Sirve el agua del grifo para regar?",
      options: ["Casi siempre sirve", "Nunca sirve", "Solo filtrada"],
      answer: 0,
      why: "En general sirve. Si el agua es muy dura, déjala reposar.",
    },
    {
      ask: "¿Una hoja amarilla que cae en la base siempre es problema?",
      options: ["Sí", "No siempre, puede ser hoja vieja", "Solo en verano"],
      answer: 1,
      why: "La planta suelta hoja vieja de forma natural. Preocúpate si son varias.",
    },
    {
      ask: "¿Para qué girar la maceta de vez en cuando?",
      options: [
        "Para nada",
        "Para que crezca pareja, no torcida a la luz",
        "Para espantar plagas",
      ],
      answer: 1,
      why: "Sin girarla crece inclinada hacia la ventana.",
    },
    {
      ask: "¿Limpiar el polvo de las hojas sirve?",
      options: [
        "Sí, respira y capta mejor la luz",
        "No sirve",
        "Solo en plantas grandes",
      ],
      answer: 0,
      why: "El polvo bloquea la luz y tapa los poros. Un paño húmedo basta.",
    },
    {
      ask: "¿Puedo usar aceite de cocina para dar brillo a la hoja?",
      options: ["Sí", "No, tapa la hoja", "Solo una gota"],
      answer: 1,
      why: "El aceite cierra los estomas y la hoja deja de respirar bien.",
    },
    {
      ask: "La planta se marchitó con la tierra mojada. ¿Qué puede ser?",
      options: ["Raíz podrida", "Falta de agua", "Poco sol"],
      answer: 0,
      why: "La raíz podrida no absorbe agua, así que se marchita nadando.",
    },
    {
      ask: "¿Cuándo conviene trasplantar?",
      options: ["Final del otoño", "Principio de primavera", "Pleno invierno"],
      answer: 1,
      why: "Entra en crecimiento y se recupera mucho más rápido.",
    },
    {
      ask: "¿Hojas nuevas pequeñas y deformes indican qué?",
      options: [
        "Falta de nutriente o plaga chupadora",
        "Exceso de luz",
        "Maceta nueva",
      ],
      answer: 0,
      why: "Conviene mirar debajo de la hoja nueva antes de abonar.",
    },
    {
      ask: "¿Planta en baño sin ventana funciona?",
      options: ["Siempre", "Solo especies de poca luz", "Nunca"],
      answer: 1,
      why: "Sin nada de luz no sobrevive ninguna. Necesita algo de claridad.",
    },
    {
      ask: "¿Pulverizar la hoja sustituye el riego?",
      options: ["Sí", "No, es solo humedad del aire", "Solo en invierno"],
      answer: 1,
      why: "La planta bebe por la raíz. Pulverizar ayuda con el aire seco.",
    },
    {
      ask: "La tierra se puso dura y el agua escurre por el lado. ¿Y ahora?",
      options: ["Regar más", "Afloja o cambia el sustrato", "Abonar"],
      answer: 1,
      why: "Compactada repele el agua. La raíz sigue sedienta aunque la mojes.",
    },
    {
      ask: "¿El sol directo de la tarde en verano va bien a la mayoría?",
      options: ["Sí", "No, suele quemar la hoja", "Solo al helecho"],
      answer: 1,
      why: "La planta de interior evolucionó bajo copas. El sol de las 14h quema.",
    },
    {
      ask: "¿Una mancha marrón con halo amarillo sugiere qué?",
      options: ["Hongo o bacteria", "Sed", "Exceso de luz"],
      answer: 0,
      why: "El halo amarillo alrededor de la mancha es señal clásica de infección.",
    },
    {
      ask: "¿Puedo plantar varios esquejes en la misma maceta?",
      options: [
        "Sí, si sus cuidados coinciden",
        "Nunca",
        "Solo si son iguales",
      ],
      answer: 0,
      why: "El problema es juntar una que bebe cada semana con un cactus.",
    },
    {
      ask: "¿Raíces asomando en la superficie son problema?",
      options: [
        "Señal de que la maceta quedó chica",
        "Siempre normal",
        "Falta de abono",
      ],
      answer: 0,
      why: "Junto con raíces por el drenaje, es la señal de trasplantar.",
    },
    {
      ask: "Tras trasplantar, ¿cuándo abonar?",
      options: ["El mismo día", "Después de unas cuatro semanas", "Nunca más"],
      answer: 1,
      why: "El sustrato nuevo ya trae nutrientes, y la raíz removida se quema fácil.",
    },
    {
      ask: "Hojas cayendo de golpe tras cambiar la planta de sitio.",
      options: [
        "Se está muriendo",
        "Estrés del cambio, suele pasar",
        "Falta de abono",
      ],
      answer: 1,
      why: "Muchas reaccionan al cambio de luz soltando hoja. Dale tiempo.",
    },
    {
      ask: "¿Enraizar un esqueje en agua o directo en tierra?",
      options: [
        "En agua es más fácil de seguir",
        "Siempre en tierra",
        "Da igual",
      ],
      answer: 0,
      why: "En agua ves nacer la raíz. Pásalo a tierra antes de que crezca mucho.",
    },
    {
      ask: "¿Qué retiene más agua, barro o plástico?",
      options: ["Barro", "Plástico", "Igual"],
      answer: 1,
      why: "El barro es poroso y evapora por los lados. Bueno si riegas de más.",
    },
    {
      ask: "¿Funciona regar por abajo, poniendo la maceta en agua?",
      options: ["Sí, de 15 a 30 minutos", "No, la ahoga", "Solo para cactus"],
      answer: 0,
      why: "La tierra sube el agua por capilaridad. Sácala cuando la superficie se humedezca.",
    },
    {
      ask: "¿La cáscara de huevo aporta calcio rápido?",
      options: [
        "Sí, al momento",
        "No, tarda muchísimo en descomponerse",
        "Nunca",
      ],
      answer: 1,
      why: "Tarda meses. No sirve para una planta que necesita nutriente ya.",
    },
    {
      ask: "¿Qué significan los tres números del abono, tipo 10-10-10?",
      options: [
        "Nitrógeno, fósforo y potasio",
        "Peso, volumen y precio",
        "Días de efecto",
      ],
      answer: 0,
      why: "N hace hoja, P raíz y flor, K resistencia general.",
    },
    {
      ask: "¿Una planta que pierde todas las hojas en invierno está muerta?",
      options: ["Siempre", "Puede estar en reposo", "Solo si es cactus"],
      answer: 1,
      why: "Muchas entran en dormancia. Rasca el tallo: verde por dentro es vida.",
    },
    {
      ask: "¿Cortar la flor marchita sirve de algo?",
      options: ["Sí, estimula nuevas flores", "No sirve", "Perjudica"],
      answer: 0,
      why: "Sin semilla que alimentar, la planta vuelve a invertir en florecer.",
    },
    {
      ask: "Cochinilla algodonosa blanca: ¿primer paso?",
      options: ["Aislar la planta de las demás", "Abonar", "Regar más"],
      answer: 0,
      why: "Camina hasta la maceta vecina. Aísla antes de tratar.",
    },
    {
      ask: "Rayas plateadas con puntitos negros indican qué?",
      options: ["Trips", "Sed", "Demasiado sol"],
      answer: 0,
      why: "El plateado es la célula vacía tras la picadura.",
    },
    {
      ask: "¿La mosca blanca desaparece sola?",
      options: ["Sí", "No, se multiplica rápido", "Solo en invierno"],
      answer: 1,
      why: "Cada hembra pone cientos de huevos. Cuanto antes trates, menos trabajo.",
    },
    {
      ask: "Llega una planta de tienda con la tierra empapada. ¿Qué haces?",
      options: ["Regar otra vez", "Dejar secar y revisar la raíz", "Abonar"],
      answer: 1,
      why: "En tienda riegan de más. Raíz marrón y blanda ya es podredumbre.",
    },
    {
      ask: "¿Poner piedras en el fondo mejora el drenaje?",
      options: ["Mucho", "Es un mito, puede empeorar", "Solo en maceta grande"],
      answer: 1,
      why: "Crea una capa donde el agua se estanca. Lo que sirve es agujero y buen sustrato.",
    },
    {
      ask: "¿Qué indica que la planta quiere más luz?",
      options: [
        "Hoja nueva pequeña y tallo estirado",
        "Hoja quemada",
        "Tierra que seca rápido",
      ],
      answer: 0,
      why: "Alarga el tallo y reduce la hoja para acercarse a la luz.",
    },
    {
      ask: "¿Y que le sobra luz?",
      options: [
        "Hoja descolorida o con mancha seca clara",
        "Hoja oscura",
        "Tallo fino",
      ],
      answer: 0,
      why: "La quemadura aclara y reseca en mancha, sin halo amarillo.",
    },
    {
      ask: "Humedad del aire: ¿cómo subirla de verdad?",
      options: [
        "Pulverizar de vez en cuando",
        "Agrupar plantas o usar bandeja con piedras y agua",
        "Cerrar la ventana",
      ],
      answer: 1,
      why: "Pulverizar sube la humedad unos minutos. Agrupar la mantiene.",
    },
    {
      ask: "¿El aire acondicionado molesta a las plantas?",
      options: ["Sí, reseca el aire", "No cambia nada", "Ayuda"],
      answer: 0,
      why: "Quita humedad del ambiente. Evita la corriente directa sobre la hoja.",
    },
    {
      ask: "Raíces enrolladas en bola: ¿qué haces al trasplantar?",
      options: [
        "Soltar y aflojar las raíces",
        "No tocarlas",
        "Cortarlas todas",
      ],
      answer: 0,
      why: "Si no las aflojas, siguen creciendo en círculo en la maceta nueva.",
    },
    {
      ask: "¿Para qué sirve la perlita en el sustrato?",
      options: ["Dar aire y drenaje", "Retener más agua", "Abonar"],
      answer: 0,
      why: "Las bolitas blancas crean huecos de aire entre la tierra.",
    },
    {
      ask: "¿Poso de café en la tierra?",
      options: [
        "Sí, poca cantidad y mezclado",
        "Todos los días, puro",
        "Nunca",
      ],
      answer: 0,
      why: "En exceso compacta y enmohece. Mejor en la compostera.",
    },
    {
      ask: "¿Las orquídeas viven en tierra común?",
      options: [
        "Sí",
        "No, necesitan corteza o sustrato aireado",
        "Solo la blanca",
      ],
      answer: 1,
      why: "Su raíz es aérea y se pudre en tierra cerrada.",
    },
    {
      ask: "¿Cuándo se riega una orquídea?",
      options: [
        "Cuando la raíz se pone blanquecina",
        "Todos los días",
        "Una vez al mes fijo",
      ],
      answer: 0,
      why: "Raíz verde es raíz hidratada. Blanquecina pide agua.",
    },
    {
      ask: "Planta tóxica para mascotas en casa: ¿mejor conducta?",
      options: [
        "Ponerla fuera del alcance y consultar al veterinario ante la duda",
        "Deshacerse siempre",
        "Ignorarlo",
      ],
      answer: 0,
      why: "La altura y una habitación cerrada resuelven la mayoría de los casos.",
    },
    {
      ask: "¿Qué le gusta al helecho?",
      options: ["Sombra con humedad", "Sol pleno", "Tierra seca"],
      answer: 0,
      why: "Viene del suelo del bosque: luz filtrada y aire húmedo.",
    },
    {
      ask: "¿Una suculenta arrugada y mustia qué significa?",
      options: ["Sed", "Exceso de agua", "Falta de abono"],
      answer: 0,
      why: "Está usando su reserva. Si se arruga hacia dentro, toca regar.",
    },
    {
      ask: "¿Hoja de suculenta blanda, translúcida y amarillenta?",
      options: ["Exceso de agua", "Sed", "Frío"],
      answer: 0,
      why: "La célula reventó de tanta agua. Esa hoja no vuelve.",
    },
    {
      ask: "¿Cuál es la mejor tijera de podar?",
      options: [
        "Cualquiera",
        "Limpia y afilada",
        "Sin filo, para no cortar de más",
      ],
      answer: 1,
      why: "El corte limpio cicatriza rápido. La hoja sucia transmite enfermedad.",
    },
    {
      ask: "¿Hay que esterilizar la tijera entre plantas?",
      options: [
        "Sí, sobre todo si una está enferma",
        "Nunca",
        "Solo en invierno",
      ],
      answer: 0,
      why: "Alcohol en la hoja evita llevar hongos de una a otra.",
    },
    {
      ask: "¿Es normal que cambie el follaje al cambiar de estación?",
      options: ["Sí, muchas se ajustan", "Nunca", "Solo si está enferma"],
      answer: 0,
      why: "Menos luz en invierno significa menos hoja. Vuelve en primavera.",
    },
    {
      ask: "¿Moho blanco en la superficie de la tierra es grave?",
      options: [
        "Suele ser exceso de humedad y poca ventilación",
        "Siempre mata la planta",
        "Es abono",
      ],
      answer: 0,
      why: "Raspa la capa, deja secar más entre riegos y mejora el aire.",
    },
    {
      ask: "¿Planta en balcón con viento fuerte todo el día?",
      options: [
        "Siempre bien",
        "El viento reseca y rompe la hoja",
        "Ayuda a crecer",
      ],
      answer: 1,
      why: "El viento constante aumenta la pérdida de agua y rompe hojas grandes.",
    },
    {
      ask: "¿Para qué sirve el abono de liberación lenta?",
      options: [
        "Alimentar poco a poco durante meses",
        "Efecto inmediato",
        "Matar plagas",
      ],
      answer: 0,
      why: "Las bolitas liberan nutriente con cada riego. Menos riesgo de quemar.",
    },
    {
      ask: "¿La sal de Epsom resuelve cualquier problema?",
      options: ["Sí", "No, solo falta de magnesio", "Nunca sirve"],
      answer: 1,
      why: "Es magnesio. Usarla sin necesidad solo acumula sal en la tierra.",
    },
  ],
};
